"""your message

Revision ID: c08084d5dd36
Revises: 
Create Date: 2025-08-04 12:39:26.623514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08084d5dd36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('book_isbn', sa.String(length=50), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('project_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('employee_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('performance_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evening_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morning_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_assignments',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('book_isbn', sa.String(length=50), nullable=False),
    sa.Column('book_title', sa.String(length=100), nullable=False),
    sa.Column('target_pages', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('task_note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('user_login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_datetime', sa.DateTime(), nullable=False),
    sa.Column('logout_datetime', sa.DateTime(), nullable=True),
    sa.Column('login_date', sa.Date(), nullable=False),
    sa.Column('leave', sa.Boolean(), nullable=True),
    sa.Column('permission', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evening_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evening_update_id', sa.Integer(), nullable=False),
    sa.Column('project_title', sa.String(length=200), nullable=True),
    sa.Column('book_isbn', sa.String(length=50), nullable=True),
    sa.Column('completed_pages', sa.Integer(), nullable=True),
    sa.Column('incompleted_pages', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_contentext_pending', sa.Boolean(), nullable=True),
    sa.Column('is_styleview_pending', sa.Boolean(), nullable=True),
    sa.Column('is_packagecreate_pending', sa.Boolean(), nullable=True),
    sa.Column('is_validation_pending', sa.Boolean(), nullable=True),
    sa.Column('is_compare_pending', sa.Boolean(), nullable=True),
    sa.Column('is_qc_pending', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['evening_update_id'], ['evening_updates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morning_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('morning_update_id', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('project_title', sa.String(length=200), nullable=True),
    sa.Column('project_description', sa.String(length=200), nullable=True),
    sa.Column('book_isbn', sa.String(length=50), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('target_pages', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['morning_update_id'], ['morning_updates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morning_tasks')
    op.drop_table('evening_tasks')
    op.drop_table('user_login_logs')
    op.drop_table('task_assignments')
    op.drop_table('morning_updates')
    op.drop_table('evening_updates')
    op.drop_table('employee_performances')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
